#!/usr/bin/env python3
"""Secret detection for pre-publication.

Runs `gitleaks` over the working tree and, when a git repository is
present, over the git history. Emits findings that carry class, carrier,
location, severity, confidence, and remediation kind.

`gitleaks` is required. When it is absent this check stops with a clear
message. There is no weaker fallback.

Read-only with respect to the project. Writes only into the output
directory.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import support  # noqa: E402

OUTPUT_SUBPATH = support.OUTPUT_SUBPATH
CONFIG_NAME = "gitleaks-prepublish.toml"

# Rule IDs that identify a private key. These are certain, not inferred.
PRIVATE_KEY_RULES = ("private-key", "private_key")

# Rule IDs that are generic rather than provider-anchored. These are
# possible, not likely.
GENERIC_RULES = ("generic-api-key", "generic")

# A provider rule needs this much Shannon entropy to be `likely`. Below
# it, the value has no context and is only `possible`.
ENTROPY_LIKELY = 3.0

# Where each credential is revoked. The agent completes the provider
# location when a rule is not listed here.
REVOCATION = {
    "github-pat": "GitHub - Settings > Developer settings > Personal access tokens",
    "github-fine-grained-pat": "GitHub - Settings > Developer settings > Personal access tokens",
    "github-oauth": "GitHub - Settings > Applications",
    "github-app-token": "GitHub - Settings > Developer settings > GitHub Apps",
    "github-refresh-token": "GitHub - Settings > Applications",
    "aws-access-token": "AWS - IAM > Users > Security credentials (delete or rotate the key)",
    "gcp-api-key": "Google Cloud - APIs & Services > Credentials",
    "slack-access-token": "Slack - app management > OAuth tokens (revoke and reinstall)",
    "slack-webhook-url": "Slack - incoming webhook settings (regenerate the URL)",
    "private-key": "the service that trusts this key (rotate the key pair)",
    "private-key-2": "the service that trusts this key (rotate the key pair)",
}
DEFAULT_REVOCATION = "the provider that issued the credential"

CONFIG_TEMPLATE = """\
# Generated by pre-publication. Do not edit.
# Extends the gitleaks default rules and excludes the skill's own
# output directory from the scan.
[extend]
useDefault = true

[[allowlists]]
description = "pre-publication output"
paths = ['''{output_pattern}''']
"""


def output_dir(project_root):
    return os.path.join(os.path.abspath(project_root), OUTPUT_SUBPATH)


def gitleaks_path(override=None):
    if override:
        return override if os.path.exists(override) else None
    return shutil.which("gitleaks")


def tool_version(path):
    result = subprocess.run([path, "version"], stdout=subprocess.PIPE,
                            stderr=subprocess.DEVNULL, text=True)
    return result.stdout.strip() or "unknown"


def write_config(path, output_pattern):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(CONFIG_TEMPLATE.format(output_pattern=output_pattern))
    return path


def run_scan(path, config, source, mode):
    """Run one gitleaks scan. Return (findings, error)."""
    handle, report = tempfile.mkstemp(prefix="prepublish-gitleaks-",
                                      suffix=".json")
    os.close(handle)
    args = [path, mode, source,
            "--config", config,
            "--no-banner",
            "--report-format", "json",
            "--report-path", report]
    try:
        result = subprocess.run(args, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, text=True)
        # gitleaks exits 1 when it finds leaks. That is a result, not an error.
        if result.returncode not in (0, 1):
            detail = (result.stderr or result.stdout).strip().splitlines()
            message = detail[-1] if detail else "exit %s" % result.returncode
            return [], message
        try:
            with open(report, "r", encoding="utf-8") as stream:
                data = json.load(stream)
        except (OSError, ValueError) as exc:
            return [], "could not read the gitleaks report: %s" % exc
        return (data or []), None
    finally:
        if os.path.exists(report):
            os.remove(report)


def confidence_for(rule_id, entropy=None):
    rule = (rule_id or "").lower()
    if any(key in rule for key in PRIVATE_KEY_RULES):
        return "certain"
    if any(rule == g or rule.startswith(g + "-") for g in GENERIC_RULES):
        return "possible"
    if entropy is None or entropy < ENTROPY_LIKELY:
        return "possible"
    return "likely"


def revocation_for(rule_id):
    return REVOCATION.get((rule_id or "").lower(), DEFAULT_REVOCATION)


def relative(path, project_root):
    if not path:
        return "unknown"
    if os.path.isabs(path):
        try:
            return os.path.relpath(path, project_root)
        except ValueError:
            return path
    return path


def location_for(item, mode, project_root):
    path = relative(item.get("File"), project_root)
    line = item.get("StartLine")
    if line:
        return "%s:%s" % (path, line)
    return path


def to_finding(item, mode, index, project_root):
    rule_id = item.get("RuleID") or "unknown"
    carrier = "working tree" if mode == "dir" else "git history"
    finding = {
        "id": "secret-%d" % index,
        "class": "secrets",
        "carrier": carrier,
        "location": location_for(item, mode, project_root),
        "severity": "critical",
        "confidence": confidence_for(rule_id, item.get("Entropy")),
        "remediation": "rotate-credential",
        "rule": rule_id,
        "description": item.get("Description") or "",
        "value": item.get("Secret") or "",
        "entropy": item.get("Entropy"),
        "commit": item.get("Commit") or None,
        "revocation": revocation_for(rule_id),
    }
    return finding


def scan(project_root, path, config):
    findings = []
    errors = []

    tree, error = run_scan(path, config, project_root, "dir")
    if error:
        errors.append("working tree: %s" % error)
    for item in tree:
        findings.append(to_finding(item, "dir", len(findings) + 1, project_root))

    if os.path.isdir(os.path.join(project_root, ".git")):
        history, error = run_scan(path, config, project_root, "git")
        if error:
            errors.append("git history: %s" % error)
        for item in history:
            findings.append(to_finding(item, "git", len(findings) + 1, project_root))

    return findings, errors


def skipped_result(reason, path=None):
    return {
        "vector": "secrets",
        "status": "skipped",
        "reason": reason,
        "tool": {"name": "gitleaks", "path": path, "version": None},
        "findings": [],
        "errors": [],
    }


def render_text(result):
    lines = ["Pre-publication secret scan", ""]
    if result["status"] == "skipped":
        lines.append("SKIPPED: %s" % result["reason"])
        return "\n".join(lines)
    tool = result["tool"]
    lines.append("tool: %s %s" % (tool["name"], tool.get("version") or ""))
    lines.append("findings: %d" % len(result["findings"]))
    for finding in result["findings"]:
        lines.append("  [%s] %s | %s | %s | confidence: %s"
                     % (finding["severity"], finding["class"],
                        finding["carrier"], finding["location"],
                        finding["confidence"]))
        lines.append("      rule: %s" % finding["rule"])
        if finding.get("commit"):
            lines.append("      commit: %s" % finding["commit"][:12])
    if result["errors"]:
        lines.append("")
        lines.append("errors:")
        for error in result["errors"]:
            lines.append("  %s" % error)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    parser.add_argument("--out", default=None,
                        help="findings JSON path (default: output dir)")
    parser.add_argument("--gitleaks", default=None,
                        help="gitleaks binary path (default: PATH lookup)")
    args = parser.parse_args()

    project_root = os.path.abspath(args.project_root)
    out_dir = output_dir(project_root)
    os.makedirs(out_dir, exist_ok=True)
    out_path = args.out or os.path.join(out_dir, "secrets.json")

    path = gitleaks_path(args.gitleaks)
    if path is None:
        reason = ("gitleaks is required and was not found. Secret detection "
                  "did not run. Install gitleaks, then run this check again.")
        result = skipped_result(reason)
        with open(out_path, "w", encoding="utf-8") as handle:
            json.dump(result, handle, indent=2)
            handle.write("\n")
        print("SKIPPED: %s" % reason, file=sys.stderr)
        return 3

    config = write_config(os.path.join(out_dir, CONFIG_NAME), r"\.local/prepublish")
    findings, errors = scan(project_root, path, config)
    result = {
        "vector": "secrets",
        "status": "ok",
        "reason": None,
        "tool": {"name": "gitleaks", "path": path,
                 "version": tool_version(path)},
        "findings": findings,
        "errors": errors,
    }
    with open(out_path, "w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2)
        handle.write("\n")

    if args.format == "json":
        print(json.dumps(result, indent=2))
    else:
        print(render_text(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
